/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from 'react'
import { KeyboardControls, useAnimations, useGLTF } from '@react-three/drei'
import Ecctrl, { EcctrlAnimation, EcctrlJoystick } from 'ecctrl'

export default function Demon(props) {

  const { nodes, materials, animations } = useGLTF('models/Demon.glb')
  const { actions } = useAnimations(animations);

  for (const material in materials) {
    materials[material].metalness = -2
    materials[material].roughness = 1
  }

  const keyboardMap = [
    { name: 'forward', keys: ['ArrowUp', 'KeyW'] },
    { name: 'backward', keys: ['ArrowDown', 'KeyS'] },
    { name: 'leftward', keys: ['ArrowLeft', 'KeyA'] },
    { name: 'rightward', keys: ['ArrowRight', 'KeyD'] },
    { name: 'jump', keys: ['Space'] },
    { name: 'run', keys: ['Shift'] },
    { name: 'action1', keys: ['1'] },
    { name: 'action2', keys: ['2'] },
    { name: 'action3', keys: ['3'] },
    { name: 'action4', keys: ['KeyF'] }
  ]

  const animationSet = {
    idle: 'CharacterArmature|Idle',
    walk: 'CharacterArmature|Walk',
    run: 'CharacterArmature|Run',
    jump: 'CharacterArmature|Jump',
    jumpIdle: 'CharacterArmature|Jump_Idle',
    jumpLand: 'CharacterArmature|Jump_Land',
    fall: 'CharacterArmature|Duck', // This is for falling from high sky
    action1: 'CharacterArmature|Wave',
    action2: 'CharacterArmature|Death',
    action3: 'CharacterArmature|HitReact',
    action4: 'CharacterArmature|Punch'
  }

  const url = "models/Demon.glb"
  console.log(animations)

  return (
    <KeyboardControls map={keyboardMap}>

    <Ecctrl
      capsuleHalfHeight={0.35}
      floatingDis={0.35}

      camInitDis={-2.5}
      camMinDis={-2}
      camMaxDis={-4}
      maxVelLimit={2}
      position={[9,11,1]}

    >
      <EcctrlAnimation characterURL={url} animationSet={animationSet}>
        <group name="Root_Scene" >
          <group name="RootNode">
            <group name="CharacterArmature" 
              rotation={[-Math.PI / 2, 0, 0]} 
              scale={30} 
              position={[0, -0.8, 0]}
              
              >
              <primitive object={nodes.Root} />
            </group>
            <group name="Demon" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
              <skinnedMesh
                name="Demon_1"
                geometry={nodes.Demon_1.geometry}
                material={materials.Demon_Main}
                skeleton={nodes.Demon_1.skeleton}
                receiveShadow
                castShadow
              />
              <skinnedMesh
                name="Demon_2"
                geometry={nodes.Demon_2.geometry}
                material={materials.Black}
                skeleton={nodes.Demon_2.skeleton}
                receiveShadow
                castShadow
              />
              <skinnedMesh
                name="Demon_3"
                geometry={nodes.Demon_3.geometry}
                material={materials.Eye_White}
                skeleton={nodes.Demon_3.skeleton}
                receiveShadow
                castShadow
              />
              <skinnedMesh
                name="Demon_4"
                geometry={nodes.Demon_4.geometry}
                material={materials.Eye_Black}
                skeleton={nodes.Demon_4.skeleton}
                receiveShadow
                castShadow
              />
            </group>
            <skinnedMesh
              name="Trident"
              geometry={nodes.Trident.geometry}
              material={materials.Black}
              skeleton={nodes.Trident.skeleton}
              position={[1.895, 1.734, -0.17]}
              scale={75.326}
              receiveShadow
              castShadow
            />
          </group>
        </group>
      </EcctrlAnimation>
    </Ecctrl>
    </KeyboardControls>

  );
};

useGLTF.preload('/models-3d/Demon.glb')
